version: "3.1"

services:
  mongo:
    image: mongo:4.4.2
    restart: always
    ports:
      - 27000:27017
    volumes:
      - ./mongodb:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${ME_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongo'
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}

  npm:
    image: node:14
    container_name: npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]

  frontend:
    image: panbanglanfeng/fanshawe-ims:mevn_frontend
    volumes:
      - ./front-end:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${FE_PORT}:8080
    environment:
      VUE_APP_API_PORT: ${BE_PORT}

  backend:
    image: panbanglanfeng/fanshawe-ims:mevn_backend
    restart: always
    depends_on:
      - mongo
    volumes:
      - ./back-end:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${BE_PORT}:3000
    # entrypoint: ["pm2", "start", "./bin/www", "--watch"]
    entrypoint: ["npm", "run", "start"]
    environment:
      MONGO_CONNECT_URL: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@mongo/${MONGO_DB_NAME}
